# /* ----------- 💫 https://github.com/JaKooLit 💫 -------- */ #

[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class alacritty-dropterm"
class = "alacritty-dropterm"
size = "40% 60%"
